default: &default
  project_id: CLICKTALE_PROJECT_ID
  ratio: 1
  param: CLICKTALE_PARAM
  
production:
  <<: *default
  enabled: true

development:
  <<: *default
  enabled: false
  
test:
  <<: *default
  enabled: false
